#!/bin/sh
# Generate modules/stdlib_src.h from every .my file in stdlib/.
# Each entry becomes a row in the lookup table — no other C edits
# needed when you add a new stdlib module.
#
# Usage: scripts/gen_stdlib.sh OUT_FILE STDLIB_DIR
#   scripts/gen_stdlib.sh modules/stdlib_src.h stdlib

set -e
OUT="$1"
DIR="$2"

if [ -z "$OUT" ] || [ -z "$DIR" ]; then
    echo "usage: $0 OUT_FILE STDLIB_DIR" >&2
    exit 2
fi

# Collect names in sorted order so the lookup table is deterministic.
names=$(ls "$DIR" | sed -n 's/\.my$//p' | sort)

{
    cat <<'HEADER'
// Auto-generated by scripts/gen_stdlib.sh from stdlib/*.my — do
// not hand-edit. To add a new module, drop a .my file into stdlib/
// and rebuild; this header is regenerated automatically.

#ifndef __STDLIB_SRC_H__
#define __STDLIB_SRC_H__

#include <stddef.h>
#include <string.h>

HEADER
    # Per-module source strings. Declared as arrays (not pointers)
    # so their addresses are compile-time constants — required for
    # the static struct initializer below.
    for n in $names; do
        echo "static const char STDLIB_SRC_$n[] ="
        awk '{gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); printf "\"%s\\n\"\n", $0}' "$DIR/$n.my"
        echo ";"
        echo
    done

    # Lookup table.
    echo "static const struct { const char *name; const char *src; } stdlib_modules[] = {"
    for n in $names; do
        echo "    {\"$n\", STDLIB_SRC_$n},"
    done
    echo "    {NULL, NULL}"
    echo "};"

    cat <<'FOOTER'

// Returns the embedded source for `name`, or NULL if not a stdlib
// module. Linear scan — fine for the handful of stdlib modules we
// have. Swap for a perfect hash if/when that ever matters.
static inline const char *stdlib_source_lookup(const char *name)
{
    if (name == NULL) return NULL;
    for (int i = 0; stdlib_modules[i].name != NULL; i++)
    {
        if (strcmp(stdlib_modules[i].name, name) == 0)
            return stdlib_modules[i].src;
    }
    return NULL;
}

#endif
FOOTER
} > "$OUT"
